// Stable, machine-readable error codes sent to clients as `code`.
// Clients may branch on them, so a published code is never renamed or reused for another meaning.
module.exports = Object.freeze({
  INVALID_QUERY: 'INVALID_QUERY',
  INVALID_IDEMPOTENCY_KEY: 'INVALID_IDEMPOTENCY_KEY',
  WALLET_INACTIVE: 'WALLET_INACTIVE',
  TOPUP_INVALID_AMOUNT: 'TOPUP_INVALID_AMOUNT',
  TOPUP_CLOSED: 'TOPUP_CLOSED',
  TOPUP_LIMIT_REACHED: 'TOPUP_LIMIT_REACHED',
  TOPUP_KEY_REUSED: 'TOPUP_KEY_REUSED',
  TOPUP_CODE_UNAVAILABLE: 'TOPUP_CODE_UNAVAILABLE',
  TOPUP_SELF_APPROVAL: 'TOPUP_SELF_APPROVAL',
  TOPUP_RECEIVED_AMOUNT_REQUIRED: 'TOPUP_RECEIVED_AMOUNT_REQUIRED',
  TOPUP_AMOUNT_MISMATCH: 'TOPUP_AMOUNT_MISMATCH',
});
