'use client';
import { useState } from 'react';
import EventImageUpload from './EventImageUpload';
import BankFields from './BankFields';
export const eventStatuses = { DRAFT: 'Bản nháp', PUBLISHED: 'Đã công bố', REGISTRATION_OPEN: 'Mở đăng ký', REGISTRATION_CLOSED: 'Đóng đăng ký', COMPLETED: 'Đã kết thúc', CANCELLED: 'Đã hủy' };
export function slugify(value) { return value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[đĐ]/g, 'd').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''); }
function localDate(value) { if (!value) return ''; const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0,16); }
export default function EventEditor({ event, organizations = [], onSave, busy }) {
  const [uploading, setUploading] = useState(false);
  const [value, setValue] = useState({ name: event?.name || '', slug: event?.slug || '', organizerId: event?.organizerId || organizations[0]?._id || '', city: event?.location.city || '', venue: event?.location.venue || '', raceDate: localDate(event?.dateInfo.raceDate), registrationStart: localDate(event?.dateInfo.registrationStart), registrationEnd: localDate(event?.dateInfo.registrationEnd), status: event?.status || 'DRAFT', bannerUrl: event?.bannerUrl || '', logoUrl: event?.logoUrl || '', bankBin: event?.bankAccountInfo?.bankBin || '', bankName: event?.bankAccountInfo?.bankName || '', accountNo: event?.bankAccountInfo?.accountNo || '', accountName: event?.bankAccountInfo?.accountName || '' });
  const change = e => setValue({ ...value, [e.target.name]: e.target.value });
  const fields = [['name','Tên giải chạy','text'],['slug','Đường dẫn (slug)','text'],['city','Tỉnh / thành phố','text'],['venue','Địa điểm xuất phát','text'],['registrationStart','Bắt đầu đăng ký','datetime-local'],['registrationEnd','Kết thúc đăng ký','datetime-local'],['raceDate','Ngày giờ thi đấu','datetime-local']];
  return <form onSubmit={e => { e.preventDefault(); onSave({ bannerUrl: value.bannerUrl, logoUrl: value.logoUrl, name: value.name, ...(!event ? { slug: value.slug, organizerId: value.organizerId } : { status: value.status }), location: { city: value.city, venue: value.venue }, dateInfo: Object.fromEntries(['raceDate','registrationStart','registrationEnd'].map(key => [key, new Date(value[key]).toISOString()])), bankAccountInfo: { bankBin: value.bankBin, bankName: value.bankName, accountNo: value.accountNo, accountName: value.accountName } }); }}><fieldset disabled={busy || uploading}><h3 className="form-subheading">Hình ảnh của giải</h3><div className="event-upload-grid">{['banner','logo'].map(kind => <EventImageUpload key={kind} kind={kind} value={value[kind + 'Url']} eventId={event?._id} onChange={url => setValue(previous => ({ ...previous, [kind + 'Url']: url }))} onBusy={setUploading} />)}</div><div className="runner-fields">
    {!event && <label className="field-wide">Đơn vị tổ chức<select required name="organizerId" value={value.organizerId} onChange={change}><option value="">Chọn đơn vị của bạn</option>{organizations.map(org => <option key={org._id} value={org._id}>{org.name}</option>)}</select></label>}
    {fields.map(([name,label,type]) => <label key={name} htmlFor={'event-' + name}>{label}<input id={'event-' + name} name={name} type={type} required readOnly={name === 'slug' && !!event} pattern={name === 'slug' ? '[a-z0-9]+(-[a-z0-9]+)*' : undefined} maxLength={type === 'text' ? 200 : undefined} value={value[name]} onChange={change} onBlur={() => { if (name === 'name' && !value.slug && !event) setValue({ ...value, slug: slugify(value.name) }); }} /></label>)}
    {event && <label>Trạng thái<select name="status" value={value.status} onChange={change}>{Object.entries(eventStatuses).map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select></label>}
  </div><p className="organizer-hint">Thời gian theo múi giờ trên thiết bị. Bắt đầu đăng ký phải trước kết thúc đăng ký, và không sau ngày thi đấu.</p><BankFields value={value} onChange={patch => setValue(previous => ({ ...previous, ...patch }))} /><div className="form-bottom"><button className="button-primary" disabled={busy || uploading}>{busy ? 'Đang lưu...' : event ? 'Lưu thông tin sự kiện' : 'Tạo sự kiện bản nháp'}</button></div></fieldset></form>;
}
