'use client';
import { useState } from 'react';
export const eventStatuses = { DRAFT: 'Bản nháp', PUBLISHED: 'Đã công bố', REGISTRATION_OPEN: 'Mở đăng ký', REGISTRATION_CLOSED: 'Đóng đăng ký', COMPLETED: 'Đã kết thúc', CANCELLED: 'Đã hủy' };
export function slugify(value) { return value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[đĐ]/g, 'd').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''); }
function localDate(value) { if (!value) return ''; const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0,16); }
export default function EventEditor({ event, organizations = [], onSave, busy }) {
  const [value, setValue] = useState({ name: event?.name || '', slug: event?.slug || '', organizerId: event?.organizerId || organizations[0]?._id || '', city: event?.location.city || '', venue: event?.location.venue || '', raceDate: localDate(event?.dateInfo.raceDate), registrationStart: localDate(event?.dateInfo.registrationStart), registrationEnd: localDate(event?.dateInfo.registrationEnd), status: event?.status || 'DRAFT', bankName: event?.bankAccountInfo?.bankName || '', accountNo: event?.bankAccountInfo?.accountNo || '', accountName: event?.bankAccountInfo?.accountName || '' });
  const change = e => setValue({ ...value, [e.target.name]: e.target.value });
  const fields = [['name','Tên giải chạy','text'],['slug','Đường dẫn (slug)','text'],['city','Tỉnh / thành phố','text'],['venue','Địa điểm xuất phát','text'],['registrationStart','Bắt đầu đăng ký','datetime-local'],['registrationEnd','Kết thúc đăng ký','datetime-local'],['raceDate','Ngày giờ thi đấu','datetime-local']];
  return <form onSubmit={e => { e.preventDefault(); onSave({ name: value.name, ...(!event ? { slug: value.slug, organizerId: value.organizerId } : { status: value.status }), location: { city: value.city, venue: value.venue }, dateInfo: Object.fromEntries(['raceDate','registrationStart','registrationEnd'].map(key => [key, new Date(value[key]).toISOString()])), bankAccountInfo: { bankName: value.bankName, accountNo: value.accountNo, accountName: value.accountName } }); }}><fieldset disabled={busy}><div className="runner-fields">
    {!event && <label className="field-wide">Đơn vị tổ chức<select required name="organizerId" value={value.organizerId} onChange={change}><option value="">Chọn đơn vị của bạn</option>{organizations.map(org => <option key={org._id} value={org._id}>{org.name}</option>)}</select></label>}
    {fields.map(([name,label,type]) => <label key={name} htmlFor={'event-' + name}>{label}<input id={'event-' + name} name={name} type={type} required readOnly={name === 'slug' && !!event} pattern={name === 'slug' ? '[a-z0-9]+(-[a-z0-9]+)*' : undefined} maxLength={type === 'text' ? 200 : undefined} value={value[name]} onChange={change} onBlur={() => { if (name === 'name' && !value.slug && !event) setValue({ ...value, slug: slugify(value.name) }); }} /></label>)}
    {event && <label>Trạng thái<select name="status" value={value.status} onChange={change}>{Object.entries(eventStatuses).map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select></label>}
  </div><p className="organizer-hint">Thời gian theo múi giờ trên thiết bị. Bắt đầu đăng ký phải trước kết thúc đăng ký, và không sau ngày thi đấu.</p><h3 className="form-subheading">Thông tin nhận chuyển khoản</h3><div className="runner-fields">{[['bankName','Ngân hàng'],['accountNo','Số tài khoản'],['accountName','Tên chủ tài khoản']].map(([key,label]) => <label key={key}>{label}<input name={key} value={value[key]} onChange={change} maxLength={120} /></label>)}</div><p className="organizer-hint">Chuyển khoản vẫn cần đối soát trước khi cấp vé.</p><div className="form-bottom"><button className="button-primary" disabled={busy}>{busy ? 'Đang lưu...' : event ? 'Lưu thông tin sự kiện' : 'Tạo sự kiện bản nháp'}</button></div></fieldset></form>;
}
