const { chromium, expect } = require('@playwright/test');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({ ...(process.env.CHROME_PATH ? { executablePath: process.env.CHROME_PATH } : { channel: 'chrome' }), headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
    const errors = []; page.on('pageerror', error => errors.push(error.message));
    let release;
    const ready = new Promise(resolve => { release = resolve; });
    await page.route('**/api/events?upcoming=true&limit=20&page=*', async route => { await ready; await route.fulfill({ json: { events: [0,1,2].map(i => ({ _id: String(i), slug: 'motion-' + i, name: 'Giải kiểm thử ' + i, categories: ['5K'], location: { city: 'Đà Lạt' } })) } }); });
    await page.goto(process.env.WEB_TEST_URL || 'http://localhost:3000', { waitUntil: 'domcontentloaded' });
    const scene = page.locator('.immersive-journey'), dialog = page.locator('.immersive-panel-dialog');
    const trigger = key => page.locator('.immersive-panel-trigger[data-panel="' + key + '"]:visible').first();
    const open = async key => {
      await trigger(key).click();
      await expect(dialog).toHaveAttribute('data-open', key);
      await expect(dialog).toHaveAttribute('role', 'dialog');
      await expect.poll(() => dialog.evaluate(node => node.contains(document.activeElement))).toBe(true);
    };
    const close = async key => {
      await page.keyboard.press('Escape');
      await expect(dialog).toBeHidden();
      await expect(trigger(key)).toBeFocused();
    };
    await expect(scene).toHaveAttribute('data-enhanced', 'true', { timeout: 20000 });
    await open('events');
    await expect(page.locator('.landing-event-grid')).toHaveAttribute('aria-busy', 'true');
    await expect(page.locator('.event-skeleton')).toHaveCount(3);
    release();
    await expect(page.locator('.landing-event-card')).toHaveCount(3);
    await expect(page.locator('.landing-event-grid')).toHaveAttribute('aria-busy', 'false');
    await close('events');
    await open('distance');
    await page.locator('#distance-tab-0').click();
    await expect(page.locator('#distance-panel a')).toHaveAttribute('href', '/events?distance=5');
    await close('distance');
    await open('guide');
    await expect(page.locator('#how-it-works')).toBeVisible();
    await page.locator('#journey-tab-1').click();
    await expect(page.locator('#journey-panel a')).toHaveAttribute('href', '/account');
    await close('guide');
    await open('distance');
    await expect(page.locator('#distance-tab-0')).toHaveAttribute('aria-selected', 'true');
    await close('distance');

    // Scrolling a long panel consumes the wheel locally without triggering another running leg.
    await page.setViewportSize({ width: 390, height: 844 });
    await open('faq');
    const checkpoint = await scene.getAttribute('data-chapter');
    const journeyProgress = await scene.evaluate(node => node.style.getPropertyValue('--journey-progress'));
    const documentScroll = await page.evaluate(() => scrollY);
    const scrollable = await dialog.evaluateHandle(node => [node, ...node.querySelectorAll('*')].find(element => /auto|scroll/.test(getComputedStyle(element).overflowY) && element.scrollHeight > element.clientHeight + 20));
    const scrollElement = scrollable.asElement();
    assert.ok(scrollElement, 'FAQ has a scrollable content region on mobile');
    await scrollElement.evaluate(node => { node.scrollTop = 0; });
    const box = await scrollElement.boundingBox();
    await page.mouse.move(box.x + box.width / 2, box.y + Math.min(box.height - 25, 160));
    await page.mouse.wheel(0, 480);
    await expect.poll(() => scrollElement.evaluate(node => node.scrollTop)).toBeGreaterThan(20);
    await page.waitForTimeout(1000);
    assert.equal(await scene.getAttribute('data-chapter'), checkpoint, 'Panel wheel preserves checkpoint');
    assert.equal(await scene.evaluate(node => node.style.getPropertyValue('--journey-progress')), journeyProgress, 'Panel wheel preserves camera progress');
    assert.equal(await page.evaluate(() => scrollY), documentScroll, 'Panel wheel does not scroll the document');
    await expect(scene).toHaveAttribute('data-activity', 'idle');
    await page.locator('.immersive-panel-close').focus();
    await page.keyboard.press('Shift+Tab');
    await expect.poll(() => dialog.evaluate(node => node.contains(document.activeElement))).toBe(true);
    await close('faq');

    await page.emulateMedia({ reducedMotion: 'reduce' });
    await expect(scene).toHaveAttribute('data-enhanced', 'false');
    await expect(page.locator('.pin-spacer')).toHaveCount(0);
    await expect(page.locator('.immersive-canvas canvas')).toHaveCount(0);
    for (const selector of ['#your-distance', '.landing-events', '#how-it-works', '#questions', '.landing-cta']) await expect(page.locator(selector)).toBeVisible();
    await page.emulateMedia({ reducedMotion: 'no-preference' });
    await expect(scene).toHaveAttribute('data-enhanced', 'true');
    await expect(page.locator('.pin-spacer')).toHaveCount(1);
    await open('distance');
    await close('distance');
    assert.deepEqual(errors, []);
    const noJS = await browser.newContext({ javaScriptEnabled: false });
    const staticPage = await noJS.newPage();
    await staticPage.goto(process.env.WEB_TEST_URL || 'http://localhost:3000');
    for (const selector of ['#your-distance', '#how-it-works', '#questions', '.landing-cta']) await expect(staticPage.locator(selector)).toBeVisible();
    await expect(staticPage.locator('.pin-spacer')).toHaveCount(0);
    assert.equal(await staticPage.locator('.journey-panel').evaluate(node => getComputedStyle(node).opacity), '1');
    await noJS.close();
    console.log('PASS: immersive panels, async events, persistent selections, focus/Escape, isolated panel wheel scrolling, reduced-motion and no-JS content.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
